// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniVault.Server.Data;

#nullable disable

namespace MiniVault.Server.Data.Migrations
{
    [DbContext(typeof(MiniVaultDbContext))]
    [Migration("20260902132524_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniVault.Server.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SecretName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SecretIterations")
                        .HasColumnType("int");

                    b.Property<byte[]>("SecretSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.ClientRole", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ClientId", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("ClientRoles", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.DataKey", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("WrappedByMaster")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("WrappedByRecovery")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Version");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("DataKeys", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.RoleRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName", "Scope");

                    b.ToTable("RoleRules", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.Secret", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DekVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("DekVersion");

                    b.ToTable("Secrets", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.VaultMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("InitializedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("KekIterations")
                        .HasColumnType("int");

                    b.Property<byte[]>("KekSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("RecoveryKeyWrappedByMaster")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RecoveryMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Shares")
                        .HasColumnType("int");

                    b.Property<int?>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VaultMetadata", (string)null);
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.ClientRole", b =>
                {
                    b.HasOne("MiniVault.Server.Data.Entities.Client", "Client")
                        .WithMany("Roles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniVault.Server.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.RoleRule", b =>
                {
                    b.HasOne("MiniVault.Server.Data.Entities.Role", null)
                        .WithMany("Rules")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.Secret", b =>
                {
                    b.HasOne("MiniVault.Server.Data.Entities.DataKey", null)
                        .WithMany()
                        .HasForeignKey("DekVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.Client", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MiniVault.Server.Data.Entities.Role", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
